#include "TFile.h"
#include "TH2F.h"
#include "TCanvas.h"

void plotHistos_tha_thb()
{
    TFile* f_sim = new TFile("../data/org_many/histos_sim_tha_thb/histos.root");
    TFile* f_real = new TFile("../data/org_many/histos_real_tha_thb/histos.root");
    
    TH2F* h_sim = 0;
    TH2F* h_real = 0;
    
    f_sim->GetObject("hdchi2",h_sim);
    f_real->GetObject("hdchi2",h_real);

    //f_sim->Close();
    //f_real->Close();

    h_sim->SetTitle("chi2 map of data generated from pdf");
    h_sim->GetXaxis()->SetTitle("tha");
    h_sim->GetYaxis()->SetTitle("thb");
    h_real->SetTitle("chi2 map of data generated by EvtGen");
    h_real->GetXaxis()->SetTitle("tha");
    h_real->GetYaxis()->SetTitle("thb");

    h_sim->SetMinimum(3000);
    h_sim->SetMaximum(10000);
    h_real->SetMinimum(3000);
    h_real->SetMaximum(10000);

    TCanvas* c1 = new TCanvas("c1","c1",1200,600);
    c1->Divide(2);
    c1->cd(1);
    h_sim->Draw();
    c1->cd(2);
    h_real->Draw();
}
